### ISSUE TITLE
[Question] Why not get a promise as a param instead of a function?

### ISSUE THREAD

**Issue by eduardosada** [open-draft/until#6]
Why is this better?

```js
const [error, user] = await until(() => fetchUser(id))
```

instead of this?

```js
const [error, user] = await until(fetchUser(id))
```

**Comment by karlhorky** [comment]
Could probably work, there are a bunch of alternatives that do that:

- https://gist.github.com/karlhorky/3593d8cd9779cf9313f9852c59260642
- https://www.npmjs.com/package/try-to-catch
- https://www.npmjs.com/package/@casperengl/try-catch
- https://www.npmjs.com/package/try-catch-js
- https://www.npmjs.com/package/trycatch (closest to [ES Proposal](https://twitter.com/karlhorky/status/1389863332669272065), also supports synchronous mode)
- https://www.npmjs.com/package/await-to-js
- https://www.npmjs.com/package/try-catch-expression
- https://www.npmjs.com/package/try-catch
- https://www.npmjs.com/package/try.catch
