### ISSUE TITLE
Incorrect Types

### ISSUE THREAD

**Issue by karlhorky** [open-draft/until#7]
Hi @kettanaito! 👋  Hope you are well :)

The return type doesn't agree with the `null` values returned here:

```ts
export const until = async <DataType = unknown, ErrorType = Error>(promise: () => Promise<DataType>): Promise<[ErrorType, DataType]> => {
  try {
    const data = await promise().catch((error) => {
      throw error
    })
    return [null, data] // 💥 Type 'null' is not assignable to type 'ErrorType'.
  } catch (error) {
    return [error, null] // 💥 Type 'null' is not assignable to type 'DataType'.
  }
}
```

Created a playground for this: https://www.typescriptlang.org/play?ssl=1&ssc=1&pln=10&pc=2#code/AQQwzgngdgxsBmBXWAXAlgeysZ6A2wAPACIgogAqEADgKbAC8OUA1lBgO5QA0wAogCcBGAVTqN+QkQD4AFNWEBbNGFoAuYLICUjacAAKSlbRJlKNWtK0bDGZasIBtQcNEXepcmNoBdPcABvAChgYBQBCECQ0OAYLDAUYAATMwkQDhA0RIU7Y20AOhgyGAALWVlaKQEdBj1gmJiUEuEOYErXaNCAXy1O4AFaFEQBbEcoRDw8XhTyH2iu2OKSzXaRHXqYgaGR4EdVgV5xybnuoK6gA

**Comment by karlhorky** [comment]
You could take a look at the approaches used in the many alternatives:

- https://gist.github.com/karlhorky/3593d8cd9779cf9313f9852c59260642
- https://www.npmjs.com/package/try-to-catch
- https://www.npmjs.com/package/@casperengl/try-catch
- https://www.npmjs.com/package/try-catch-js
- https://www.npmjs.com/package/trycatch (closest to [ES Proposal](https://twitter.com/karlhorky/status/1389863332669272065), also supports synchronous mode)
- https://www.npmjs.com/package/await-to-js
- https://www.npmjs.com/package/try-catch-expression
- https://www.npmjs.com/package/try-catch
- https://www.npmjs.com/package/try.catch

**Comment by karlhorky** [comment]
My favorite approach boils down to using an object, a union in the return type, and then not destructuring:

```ts
async function tryCatch<Data>(
  promise: Promise<Data>,
): Promise<{ error: Error } | { data: Data }> {
  try {
    return { data: await promise };
  } catch (error) {
    return { error };
  }
}
```

**Usage:**

```ts
const result = await tryCatch(promise);

if ('error' in result) return handleError(result.error);

// Here TypeScript is certain that result.data exists:
doSomethingAwesome(result.data);
```

**Comment by kettanaito** [comment]
Hey. Thanks for raising this. Must be a TS version issue, this library was written quite some time ago.

We may just specify that each value in the tuple is potentially `null` [like so](https://www.typescriptlang.org/play?ssl=1&ssc=1&pln=10&pc=2#code/AQQwzgngdgxsBmBXWAXAlgeysZ6A2wAPACIgogAqEADgKbAC8OUA1lBgO5QA0wAogCcBGAVTqN+QkQD4AFNWEBbNGFoAuYLICUjacAAKSlbRJlKNWtK0bDGZasIBtQcNEXgAH2BREePL1JyMXovHz8AXT1gAG8AKGBgFAEIGPiE4BgsMBRgABMzCRAOEDQchTtjbQA6GDIYAAtZWVopAR0GPTj09JR64Q5gFtc0hIBfLRHgAVoURAFsRzD-PLNwtNGMuvrNIZEdLvTp2fngR12BXiW1sdjRoA). Do you see any issue with this approach?

**Comment by kettanaito** [comment]
I favor using an array for 2 reasons:

1. If forces the order of returned data. It equally forces you to declare an error variable _and handle it_. Objects would allow importing only what you need, being order-insensitive.

```js
const [parsingError, result] = await until(() => parse(ast))

// as opposed to
const { data: result } = await until(() => parse(ast))
```

2. `data` is way too generic and will almost always be aliased to something else. By using an array not only the library saves you the need to alias an object property, but also forces you to give more cognitive effort when naming it. Using an object may have a downside of people just sticking with `{ data }` because it's shorter and aliasing takes time. I'd argue that array makes you name things better in this case, although very slightly.

**Comment by karlhorky** [comment]
> We may just specify that each value in the tuple is potentially `null` [like so](https://www.typescriptlang.org/play?ssl=1&ssc=1&pln=10&pc=2#code/AQQwzgngdgxsBmBXWAXAlgeysZ6A2wAPACIgogAqEADgKbAC8OUA1lBgO5QA0wAogCcBGAVTqN+QkQD4AFNWEBbNGFoAuYLICUjacAAKSlbRJlKNWtK0bDGZasIBtQcNEXgAH2BREePL1JyMXovHz8AXT1gAG8AKGBgFAEIGPiE4BgsMBRgABMzCRAOEDQchTtjbQA6GDIYAAtZWVopAR0GPTj09JR64Q5gFtc0hIBfLRHgAVoURAFsRzD-PLNwtNGMuvrNIZEdLvTp2fngR12BXiW1sdjRoA). Do you see any issue with this approach?

Nice, yeah, that was one approach that I tried early on, which makes the error in the library code go away. 🙌  However, it means that you always need to check against `null`:

```ts
(async function () {
  const [error, data] = await until<{firstName: string}>(() => Promise.resolve({firstName: 'karl'}))
  console.log(data.firstName) // 💥 Object is possibly 'null'.
})()
```

[Playground](https://www.typescriptlang.org/play?ssl=15&ssc=5&pln=12&pc=1#code/AQQwzgngdgxsBmBXWAXAlgeysZ6A2wAPACIgogAqEADgKbAC8OUA1lBgO5QA0wAogCcBGAVTqN+QkQD4AFNWEBbNGFoAuYLICUjacAAKSlbRJlKNWtK0bDGZasIBtQcNEXgAH2BREePL1JyMXovHz8AXT1gAG8AKGBgFAEIGPiE4BgsMBRgABMzCRAOEDQchTtjbQA6GDIYAAtZWVopAR0GPTj09JR64Q5gFtc0hIBfLRHgAVoURAFsRzD-PLNwtNGMuvrNIZEdLvTp2fngR12BXiW1sdjR2NjZcGg4JFRMbG1UhMyobNPz3j5cjhQrFUrMfCEaLwNACbIAORAinUwGyAjQUAA5qM5J8OgYjKoqtMwBg8AA3WiyaGwhFIlEAchYIAEeAZ4wm3yyZNoVTwGExsiBICqMLhKERyIm420QA)

One pattern that is common is to handle the errors early (either `throw` or `return`). However, this doesn't work with the `| null` on each array element:

```ts
(async function () {
  const [error, data] = await until<{firstName: string}>(() => Promise.resolve({firstName: 'karl'}))
  if (error) throw new Error('oh no');
  console.log(data.firstName) // 💥 Object is possibly 'null'.
})()
```

[Playground](https://www.typescriptlang.org/play?#code/AQQwzgngdgxsBmBXWAXAlgeysZ6A2wAPACIgogAqEADgKbAC8OUA1lBgO5QA0wAogCcBGAVTqN+QkQD4AFNWEBbNGFoAuYLICUjacAAKSlbRJlKNWtK0bDGZasIBtQcNEXgAH2BREePL1JyMXovHz8AXT1gAG8AKGBgFAEIGPiE4BgsMBRgABMzCRAOEDQchTtjbQA6GDIYAAtZWVopAR0GPTj09JR64Q5gFtc0hIBfLRHgAVoURAFsRzD-PLNwtNGMuvrNIZEdLvTp2fngR12BXiW1sdjR2NjZcGg4JFRMbG1UhMyobNPz3j5cjhQrFUrMfCEaLwNACbIAORAinUwGyAjQUAA5qM5J8OgYjKoqtMwBg8AA3WiyaGwhFIlEAchYIAEeAZ4wmCTQ8B2rR0vX63loAxcIlkDIw23YDK0AG40j9SXhaFU8BhMbIgSAqjC4ShEcidAB6I3AQC8G4BSneAAHkAEYAK1oMByKmA1AwYDAaFteBSDKWDKqty02iAA)

---

One solution is to make the return type into a union return type (like `Promise<[ErrorType, null] | [null, DataType]>`):

[Playground](https://www.typescriptlang.org/play?ssl=16&ssc=5&pln=12&pc=1#code/AQQwzgngdgxsBmBXWAXAlgeysZ6A2wAPACIgogAqEADgKbAC8OUA1lBgO5QA0wAogCcBGAVTqN+QkQD4AFNWEBbNGFoAuYLICUjacAAKSlbRJlKNWtK0bDGZasIBtQcNEXeURHjwBdYAB9gR09vXlJyMVofPWAAbwAoYGAUAQg4xKTgGCwwFGAAEzMJEA4QNDyFO2NtADoYMhgAC1lZWikBHQY9BMzMlEbhDmA21wykgF8tMeABWhREAWxgrzxeQvIfDPGshsbNEZEdHszZ+cWgg4EPFc2J+PH4+NlwaDgkVExsbXSk7Khcma0MBePJMEplPK4NB4QixeBoAS5AByIEU6mAuQEaCgAHNxnJvl0DEZVDVZmAMHgAG60WRwhHI1HogDkLBAAjwzMmUySaHgmnJIMcAAYfDp+oNgFBaEMXCJZMyMHt2MytABuDJ-Cl4Wg1PAYHGyQV4FCOACMPhq8MRKBRaJ0AHoHcBAKDkwAgIAgvEiAGUYFjqHlGuBko16FicY08igLABCe5abRAA)

**Comment by kettanaito** [comment]
The thing is, whether `data` or `error` is null can only be known at runtime. TypeScript is here to reflect the expectation, and I believe expecting both as null is good, as you should always expect things to fail.

Using object return type doesn't help here either because, once again, the actual value type can only be known on runtime. We can trick TypeScript into thinking otherwise, but then we'd be taking proper error handling away.

At this point, it's no longer a discussion about what return the `until` should have, rather about the build-time/runtime data validation. I'd recommend treating both `error` and `data` as potentially null and explicitly declaring `data` as present after you handled an potential error:

```ts
const [parsingError, maybeResult] = await until(() => parse(ast))

invariant(parsingError, 'Huh, failed')

// The errors are handled, at this point I explicitly mark result as expected.
const result = maybeResult!
```

**Comment by kettanaito** [comment]
I understand you can do a union type specifying that `data`/`error` relation, but I'm not certain about it.

**Comment by karlhorky** [comment]
> The thing is, whether data or error is null can only be known at runtime. TypeScript is here to reflect the expectation, and I believe expecting both as null is good, as you should always expect things to fail.

Hmm, I'm not sure there is actually a failure case here.

Based on the code, there are only two cases:

1. `[ErrorType, null]`
2. `[null, DataType]`

So you already know if one is null that the other exists - there are no other code paths.

There is no runtime unsoundness in this approach from what I can see here...

**Comment by kettanaito** [comment]
I'm adopting the object return type in [2.0](https://github.com/open-draft/until/releases/tag/v2.0.0). Property renaming is a little price to pay for proper type safety. 

Thanks for the discussion on this, @karlhorky!
