### ISSUE TITLE
Question: Why use .catch on the promise

### ISSUE THREAD

**Issue by terenced** [open-draft/until#9]
I am curious why this [change](https://github.com/open-draft/until/commit/52bf098c100b2e9f2365bd39f3f1b8b7c1011983)  was introduced.

```typescript
// Original implementation  
export const until = async <DataType = unknown, ErrorType = Error>(promise: () => Promise<DataType>): Promise<[ErrorType, DataType]> => {
  try {
    const data = await promise()
    return [null, data]
  } catch (error) {
    return [error, null]
}
// Current implementation 
export const until = async <DataType = unknown, ErrorType = Error>(promise: () => Promise<DataType>): Promise<[ErrorType, DataType]> => {
  try {
   const data = await promise().catch((error) => { // .catch added
      throw error
    })
    return [null, data]
  } catch (error) {
    return [error, null]
}
```

Is there a benefit of calling `.catch` on the promise? It is my understanding that the catch block would handle throws?

**Comment by newpost** [comment]
@terenced can you tell me why?thank you

**Comment by kettanaito** [comment]
The `.catch()` block was added to propagate unhandled exceptions to the library. 

When there's an exception thrown during a Promise, it will _not_ be caught by a `try/catch` block around it:

```js
try { new Promise(() => { throw new Error('Hey') }) } catch (e) { console.log(e) }
```
> The `console.log` will never be called. The thrown exception will be printed as an `UnhandledPromiseRejectionWarning`.

Flow-wise, that is still an unsuccessful promise execution, so this library should execute the `return [error, null]` closure for the dependent code to handle it like an error. Adding an explicit `.catch()` statement to the given promise catches _any_ errors occurring in that promise. 

This solution also doesn't interfere with you defining your custom `.catch()`, as catch doesn't have an accumulative nature. If you've defined your custom `.catch()` block, it will get executed _first_, and the library's `.catch()` will not, unless you throw another exception in your own catch block. 

```js
new Promise(() => { throw new Error('Hey') }).catch(e => console.log('Custom', e)).catch(e => console.log('Library', e))
```

**Comment by terenced** [comment]
@kettanaito Thank you!

**Comment by sbking** [comment]
@kettanaito I think this might be incorrect - [`await` should throw on promise rejection](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Operators/await#promise_rejection) 

In your example you're just missing an `await` - add it and `console.log` is called
